require:
  - rubocop-katalyst
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  Exclude:
    - Rakefile
    - bin/*
    - config/**/*
    - db/**/*
    - spec/dummy/bin/*
    - spec/dummy/config/**/*
    - spec/dummy/db/**/*
    - vendor/bundle/**/*
  TargetRubyVersion: 3.1

# Disable cops that conflict with legacy Koi practices to reduce noise

Naming/PredicateName:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - lib/tasks/*
    - spec/**/*
