require:
  - rubocop-katalyst

AllCops:
  Exclude:
    - spec/dummy/bin/*
    - spec/dummy/config/**/*
    - spec/dummy/db/**/*
    - vendor/bundle/**/*
  TargetRubyVersion: 3.2

# Disable cops that conflict with legacy Koi practices to reduce noise

Naming/PredicateName:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - lib/tasks/*
    - spec/**/*

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Exclude:
    - spec/generators/**/*
    - spec/system/**/*
