inherit_from: .rubocop_todo.yml

require:
  - rubocop-katalyst

# Disable cops that conflict with legacy Koi practices to reduce noise

Naming/PredicateName:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false
