inherit_from:
  - .rubocop/thoughtbot.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

# https://raw.githubusercontent.com/thoughtbot/guides/master/style/ruby/.rubocop.yml


AllCops:
  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - node_modules/**/*
    - vendor/bundle/**/*
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/DotPosition:
  EnforcedStyle: leading

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/LineLength:
  Max: 120

Lint/BooleanSymbol:
  Exclude:
    - spec/**/*

Rails/DynamicFindBy:
  Whitelist:
    - find_by_hashid
    - find_by_hashid!
    - find_by_sql

RSpec/ExampleLength:
  Exclude:
    - spec/features/*

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
  Exclude:
    - app/views/**/*.jb

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

RSpec/ExampleLength:
  Max: 25
