inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-katalyst

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - spec/dummy/bin/*
    - spec/dummy/config/**/*
    - spec/dummy/db/**/*
    - spec/dummy/tmp/**/*
  TargetRubyVersion: 3.4

RSpec/MultipleExpectations:
  Exclude:
    - spec/generators/**/*

RSpec/ExampleLength:
  Exclude:
    - spec/generators/**/*
