inherit_from: .rubocop_todo.yml

require:
  - rubocop-katalyst

AllCops:
  Exclude:
    - "Rakefile"
    - "bin/*"
    - "spec/dummy/db/schema.rb"
    - "vendor/bundle/**/*"
  TargetRubyVersion: 3.1

# Disable cops that conflict with legacy Koi practices to reduce noise

Naming/PredicateName:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false
