require 'devise'
require 'dragonfly'
require 'scoped_search'
require 'acts-as-taggable-on'
require 'nested_set'
require 'kaminari'
require 'friendly_id'
require 'inherited_resources'
require 'has_scope'
require 'koi_config'
require 'has'
require 'factory_girl'
require 'simple_form'
require 'simple_navigation'
require 'uuidtools'
require 'has_crud/has_crud'
require 'has_navigation/has_navigation'
require 'koi_cms/koi_cms'
require 'koi/menu'
require 'koi/asset'
require 'koi/assets/image'
require 'koi/assets/document'
require 'koi/engine'

module Koi
end
