# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

# define test:prepare – extended by dartsass etc
namespace :test do
  task :prepare
end

namespace :dartsass do
  task clobber: :environment do
    # dartsass currently only removes top-level css files, but not koi/*
    sh "rm -rf app/assets/builds/*"
  end
end

Rails.application.load_tasks
