# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

# define test:prepare – extended by dartsass etc
namespace :test do
  task :prepare
end

Rails.application.load_tasks
